"use client";

import Link from "next/link";
import { useI18n } from "@/lib/i18n";

export default function KVKKPage() {
  const { lang } = useI18n();
  const isTr = lang === "tr";
  const sections = isTr
    ? [
        ["1. Veri Sorumlusu ve Rolleri", "HeptaCert platformu Samet Ünsal tarafından bireysel olarak işletilmektedir (\"Heptapus Group\" bir marka adıdır; tescilli bir şirket unvanı değildir). Platformun üyelik, hesap güvenliği, sistem kayıtları ve platform işletimi kapsamındaki verilerde işleten, işleme bağlamına göre veri sorumlusu veya veri işleyen sıfatıyla hareket edebilir. İletişim: contact@heptapusgroup.com"],
        ["2. Etkinlik Düzenleyicisinin Rolü", "Etkinlik kayıt sürecinde toplanan ad-soyad, iletişim bilgisi, TC kimlik no, pasaport no, öğrenci no, doğum tarihi, adres, form yanıtları, belge yüklemeleri ve benzeri etkinliğe özgü verilerde etkinliği düzenleyen kişi/kurum ayrıca bağımsız veri sorumlusu olabilir. Bu alanların hangi amaçla toplandığı, hangi hukuki sebebe dayandığı, kimlerle paylaşıldığı ve ne kadar süre saklandığı organizatörün sorumluluğundadır."],
        ["3. İşlenen Veri Kategorileri", "Kimlik ve iletişim verileri, hesap/oturum verileri, işlem geçmişi, ödeme referansları, güvenlik logları ve kullanıcı tarafından etkinlik bazında girilen ek veriler işlenebilir."],
        ["4. İşleme Amaçları", "Hesap açılışı, kimlik doğrulama, etkinlik kayıt operasyonu, sertifika üretimi, ödeme süreçleri, güvenlik, dolandırıcılık önleme, destek hizmetleri ve yasal yükümlülüklerin yerine getirilmesi amaçlarıyla veri işlenir."],
        ["5. Hukuki Sebepler", "Veriler; sözleşmenin kurulması/ifası, hukuki yükümlülüklerin yerine getirilmesi, meşru menfaat ve gerektiğinde açık rıza hukuki sebeplerine dayanılarak işlenir. Etkinlik düzenleyicileri kendi hukuki sebep seçimi ve aydınlatma yükümlülüklerinden sorumludur."],
        ["6. Kişisel Verilerin Aktarımı, Yurt Dışı Sunucular ve Hetzner Altyapısı", "HeptaCert hizmetlerinin sunulması, platform altyapısının işletilmesi, kullanıcı ve etkinlik kayıtlarının tutulması, sertifika oluşturma süreçlerinin yürütülmesi, sistem güvenliğinin sağlanması, yedekleme, bakım, teknik destek, hata kayıtlarının incelenmesi, siber güvenlik önlemlerinin uygulanması ve hizmet sürekliliğinin sağlanması amaçlarıyla kişisel verileriniz elektronik ortamda işlenebilir. HeptaCert, teknik altyapı ve sunucu barındırma hizmetleri kapsamında Hetzner Online GmbH tarafından sağlanan sunucu ve veri merkezi altyapısından yararlanmaktadır. HeptaCert ile Hetzner Online GmbH arasında veri işleme faaliyetlerine ilişkin Data Processing Agreement / Veri İşleme Sözleşmesi akdedilmiştir. Bu sözleşme kapsamında Hetzner Online GmbH, kişisel verileri altyapı ve barındırma hizmetlerinin sağlanması amacıyla, uygun teknik ve organizasyonel tedbirleri uygulayarak ve HeptaCert’in talimatları doğrultusunda işler. Kullanılan sunucular Finlandiya'nın Helsinki bölgesinde bulunmaktadır. Bu nedenle HeptaCert tarafından işlenen kişisel verileriniz, hizmetin sunulması için gerekli olduğu ölçüde Finlandiya'nın Helsinki bölgesinde bulunan sunucularda saklanabilir, işlenebilir, yedeklenebilir veya teknik olarak erişilebilir hale gelebilir. Bu kapsamda yurt dışına aktarılabilecek kişisel veriler; kimlik bilgileri, iletişim bilgileri, kullanıcı hesabı bilgileri, etkinlik kayıt bilgileri, sertifika bilgileri, işlem güvenliği bilgileri, log kayıtları, IP adresi, cihaz ve tarayıcı bilgileri ile hizmetin niteliğine göre kullanıcı tarafından sisteme girilen diğer bilgilerden oluşabilir. Yurt dışına aktarım; 6698 sayılı Kişisel Verilerin Korunması Kanunu, ilgili ikincil mevzuat ve Kişisel Verileri Koruma Kurulu kararlarına uygun olarak, ilgili aktarım şartlarının mevcut olması halinde gerçekleştirilir. Aktarım, hizmetin ifası, sistem güvenliği, veri yedekleme, teknik altyapı yönetimi ve sözleşmesel yükümlülüklerin yerine getirilmesi amaçlarıyla sınırlıdır. HeptaCert, kişisel verilerin yurt dışında işlenmesi sürecinde uygun teknik ve idari tedbirlerin alınması için makul özeni gösterir. Hetzner Online GmbH, altyapı sağlayıcısı sıfatıyla kişisel verileri yalnızca barındırma ve teknik altyapı hizmetlerinin sağlanması amacıyla işleyebilir."],
        ["6.a Yapay Zekâ Asistanlarına Aktarım", "Kullanıcı HeptaCert hesabını ChatGPT eklentisi veya MCP uyumlu başka bir yapay zekâ asistanına bağladığında, kullanıcının asistandan istediği işlem için gereken veriler (ör. etkinlik bilgileri, katılımcı adı ve e-posta adresi, check-in ve sertifika durumu) asistan sağlayıcısına (ChatGPT için OpenAI, L.L.C., ABD) aktarılır. Bu aktarım kullanıcının bağlantıyı kurması ve talepte bulunmasıyla gerçekleşir; ayrıntılar Gizlilik Politikası'ndaki Yapay Zekâ Asistanı Entegrasyonları bölümündedir."],
        ["7. Saklama Süresi", "Kişisel veriler aşağıdaki kategoriler bazında belirtilen süreler boyunca saklanır ve süre sonunda silinir, yok edilir veya anonimleştirilir: Hesap ve kimlik bilgileri hesabın aktif olduğu süre + 2 yıl; ödeme ve fatura kayıtları 10 yıl (Vergi Usul Kanunu md. 253); sertifika kayıtları hesabın aktif olduğu süre; etkinlik ve katılımcı kayıtları etkinlik tarihinden itibaren 3 yıl; güvenlik ve sistem logları 1 yıl; destek talepleri kapanış tarihinden itibaren 2 yıl. Hesap silme talebini takiben kişisel veriler yasal saklama zorunlulukları dışında 30 gün içinde silinir veya anonimleştirilir."],
        ["8. Veri Güvenliği", "HeptaCert; HTTPS/TLS ile şifreli bağlantı, parola hashleme, rol ve organizasyon bazlı erişim yetkilendirmesi, OAuth kapsam (scope) sınırları, kayıt izleme, oran sınırlama, yedekleme ve sunucu güvenliği gibi makul teknik ve idari tedbirler uygular. Sunucu altyapısı, Veri İşleme Sözleşmesi (Data Processing Agreement) akdedilmiş olan Hetzner Online GmbH tarafından Finlandiya'nın Helsinki bölgesinde sağlanır; bu sözleşme teknik ve organizasyonel tedbirler, gizlilik yükümlülükleri, veri ihlali bildirimleri, alt işleyen kullanımı ve denetim/destek süreçlerini düzenler. Kişisel verilerin bulunduğu sistemlere erişim yalnızca yetkilendirilmiş kişilerle sınırlıdır. İnternet üzerinden sunulan hiçbir sistem için mutlak güvenlik garantisi verilemez."],
        ["9. Haklarınız", "KVKK md. 11 kapsamında; kişisel verilerinizin işlenip işlenmediğini öğrenme, işlenmişse bilgi talep etme, işlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme, yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri öğrenme, eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini isteme, işlenmesini gerektiren sebeplerin ortadan kalkması hâlinde silinmesini veya yok edilmesini isteme, işleme itiraz etme ve zararın giderilmesini talep etme haklarına sahipsiniz. Veri taşınabilirliği (portabilite) kapsamında, hesabınıza giriş yaptıktan sonra ayarlar sayfasından kişisel verilerinizi makine tarafından okunabilir formatta (JSON) indirebilirsiniz. Talebin niteliğine göre başvuru ilgili veri sorumlusuna (HeptaCert işleteni Samet Ünsal veya etkinlik düzenleyicisi) contact@heptapusgroup.com adresi üzerinden yönlendirilmelidir. Başvurular en geç 30 gün içinde sonuçlandırılır; sonuçtan memnun kalmazsanız Kişisel Verileri Koruma Kurulu'na şikâyette bulunabilirsiniz."],
        ["10. İlgili Metinler", "Kişisel verilerinizin işlenmesine ilişkin ayrıntılı bilgiye Gizlilik Politikası ve Açık Rıza Metni üzerinden ulaşabilirsiniz."],
      ]
    : [
        ["1. Data Controller and Roles", "The HeptaCert platform is operated by Samet Ünsal as an individual (\"Heptapus Group\" is a brand name, not a registered company). For membership, account security, system logs, and platform operations, the operator may act as a data controller or data processor depending on processing context. Contact: contact@heptapusgroup.com"],
        ["2. Event Organizer Role", "For event-specific registration data such as attendee details, national ID/passport numbers, student numbers, date of birth, address, custom form responses, and uploaded documents, the event organizer may also act as an independent data controller. The organizer is responsible for the collection purpose, legal basis, retention period, and notices applicable to those fields."],
        ["3. Data Categories", "Identity and contact data, account/session data, transaction records, payment references, security logs, and additional event-level data provided by users may be processed."],
        ["4. Processing Purposes", "Data is processed for account setup, authentication, event registration operations, certificate generation, payments, security, fraud prevention, support, and legal compliance."],
        ["5. Legal Bases", "Processing may rely on contract performance, legal obligations, legitimate interests, and explicit consent where required. Event organizers remain responsible for selecting legal basis and providing notice for their own processing."],
        ["6. Personal Data Transfers, Overseas Servers and Hetzner Infrastructure", "Your personal data may be processed electronically for the purposes of providing HeptaCert services, operating the platform infrastructure, creating and managing user accounts, carrying out event registration processes, generating certificates, supporting payment and invoicing processes, ensuring system security, performing backups, maintenance, technical support, reviewing error logs, implementing cybersecurity measures and ensuring service continuity. HeptaCert uses server and data center infrastructure provided by Hetzner Online GmbH for technical infrastructure and server hosting services. HeptaCert has entered into a Data Processing Agreement with Hetzner Online GmbH regarding data processing activities. Under this agreement, Hetzner Online GmbH acts as an infrastructure and hosting provider and processes personal data only for the purposes of providing hosting and technical infrastructure services, in accordance with HeptaCert’s instructions and applicable technical and organizational measures. The servers used are located in Helsinki, Finland. Therefore, your personal data may be stored, processed, backed up or technically made accessible on servers located in Helsinki, Finland to the extent necessary for the provision of the service. The personal data that may be transferred abroad based on your processing activities may include identity information, contact information, user account information, event registration information, certificate information, transaction security information, log records, IP address, device and browser information and other information entered into the system depending on the nature of the service. International transfer is carried out in compliance with Turkish Personal Data Protection Law No. 6698, applicable secondary legislation and relevant decisions of the Personal Data Protection Board, where the applicable transfer conditions exist. The transfer is limited to the purposes of service performance, system security, data backup, technical infrastructure management and contractual compliance. HeptaCert takes reasonable care to ensure that appropriate technical and organizational safeguards are in place when personal data is processed abroad. Hetzner Online GmbH may process personal data only for the provision of hosting and technical infrastructure services as an infrastructure provider."],
        ["6.a Transfers to AI Assistants", "When a user connects their HeptaCert account to the ChatGPT plugin or another MCP-compatible AI assistant, the data needed for the action the user asks for (e.g. event details, attendee name and email address, check-in and certificate status) is transferred to the assistant provider (for ChatGPT: OpenAI, L.L.C., USA). The transfer happens because the user sets up the connection and makes the request; details are in the AI Assistant Integrations section of the Privacy Policy."],
        ["7. Retention Periods", "Personal data is retained per category as follows and then deleted, destroyed, or anonymized: Account and identity data — for the duration of account activity + 2 years; payment and invoice records — 10 years (Turkish Tax Procedure Law Art. 253); certificate records — for the duration of account activity; event and attendee records — 3 years from the event date; security and system logs — 1 year; support tickets — 2 years from closure. Following an account deletion request, personal data is deleted or anonymized within 30 days, except where legal retention obligations apply."],
        ["8. Security", "HeptaCert applies reasonable technical and administrative measures including HTTPS/TLS, password hashing, role- and organization-based access control, OAuth scope limits, logging, rate limiting, backups and server hardening. Server infrastructure is provided in Helsinki, Finland by Hetzner Online GmbH under a Data Processing Agreement covering technical and organizational measures, confidentiality obligations, personal data breach notifications, use of subprocessors and audit/support processes. Access to systems containing personal data is limited to authorized persons. No internet-based system can be guaranteed to be absolutely secure."],
        ["9. Your Rights", "Under applicable data protection law, you have the right to: learn whether your personal data is being processed; request information about processing; learn the purpose of processing and whether it is used appropriately; learn third parties to whom your data is transferred domestically or abroad; request correction of incomplete or incorrect data; request deletion or destruction when processing conditions no longer exist; object to processing; and request compensation for damages. For data portability (GDPR Art. 20 / KVKK Art. 11), you may download your personal data in a machine-readable format (JSON) from the settings page after logging in to your account. Please submit requests to contact@heptapusgroup.com, directed to the relevant data controller (HeptaCert's operator Samet Ünsal or the event organizer, as applicable). Requests are concluded within 30 days at the latest; if you are not satisfied, you may complain to the Turkish Personal Data Protection Board or, if you are in the European Union, to your local data protection supervisory authority."],
        ["10. Related Texts", "You can access detailed information regarding the processing of your personal data through the Privacy Policy and Explicit Consent Text."],
      ];

  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <div className="mb-8 flex items-center gap-2 text-sm text-content-muted">
        <Link href="/" className="transition-colors hover:text-brand-600">{isTr ? "Ana Sayfa" : "Home"}</Link>
        <span>/</span>
        <span className="font-medium text-content-secondary">{isTr ? "KVKK Aydınlatma Metni" : "Privacy Disclosure Notice"}</span>
      </div>

      <div className="space-y-8 rounded-2xl border border-outline-subtle bg-raised p-8 shadow-card md:p-12">
        <div>
          <p className="mb-2 text-xs font-semibold uppercase tracking-widest text-brand-600">{isTr ? "Hukuki Bilgilendirme" : "Legal Notice"}</p>
          <h1 className="text-3xl font-extrabold text-content-primary">{isTr ? "KVKK Aydınlatma Metni" : "Privacy Disclosure Notice"}</h1>
          <p className="mt-2 text-sm text-content-muted">{isTr ? "Son güncelleme: 3 Ekim 2026" : "Last updated: October 3, 2026"}</p>
        </div>

        {sections.map(([title, body]) => (
          <section key={title} className="space-y-3">
            <h2 className="text-lg font-bold text-content-primary">{title}</h2>
            <p className="text-sm leading-relaxed text-content-secondary">{body}</p>
          </section>
        ))}

        <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-outline-subtle bg-canvas p-5">
          <div>
            <p className="text-xs text-content-muted">{isTr ? "Sorularınız için" : "For questions"}</p>
            <a href="mailto:contact@heptapusgroup.com" className="text-sm font-semibold text-brand-600 hover:underline">contact@heptapusgroup.com</a>
          </div>
          <div className="flex flex-wrap gap-3">
            <Link href="/gizlilik" className="text-sm text-content-muted transition-colors hover:text-brand-600">{isTr ? "Gizlilik Politikası" : "Privacy Policy"}</Link>
            <Link href="/acik-riza" className="text-sm text-content-muted transition-colors hover:text-brand-600">{isTr ? "Açık Rıza Metni" : "Explicit Consent Text"}</Link>
            <Link href="/kullanim-kosullari" className="text-sm text-content-muted transition-colors hover:text-brand-600">{isTr ? "Kullanım Koşulları" : "Terms of Use"}</Link>
            <Link href="/iletisim" className="text-sm text-content-muted transition-colors hover:text-brand-600">{isTr ? "İletişim" : "Contact"}</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
