"""Default system email templates used by CRM, automation, and event emails."""


def _heptacert_email(preheader: str, body: str, cta_label: str | None = None, cta_url: str | None = None) -> str:
    cta = ""
    if cta_label and cta_url:
        cta = f"""
        <div class="button-container">
          <a href="{cta_url}" class="btn" target="_blank" rel="noopener noreferrer">{cta_label}</a>
        </div>
        <div class="fallback-link">
          If the button does not work, copy this link:<br>
          <a href="{cta_url}" target="_blank" rel="noopener noreferrer">{cta_url}</a>
        </div>
        """
    return f"""<!DOCTYPE html>
<html lang="tr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HeptaCert</title>
  <style>
    body {{ margin:0; padding:0; background:#ffffff; color:#1d1d1f; font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; -webkit-font-smoothing:antialiased; }}
    .wrapper {{ width:100%; background:#ffffff; padding:40px 0; }}
    .container {{ width:100%; max-width:560px; margin:0 auto; padding:20px; }}
    .header-table {{ width:100%; border-bottom:1px solid #f5f5f7; padding-bottom:20px; margin-bottom:40px; }}
    .brand-title {{ font-size:20px; font-weight:700; letter-spacing:-.5px; color:#000000; }}
    .product-tag {{ font-size:12px; font-weight:500; color:#86868b; text-transform:uppercase; letter-spacing:1px; }}
    .preheader {{ display:none!important; visibility:hidden; opacity:0; color:transparent; height:0; width:0; overflow:hidden; }}
    .content {{ font-size:15px; line-height:1.65; color:#1d1d1f; }}
    .content p {{ margin:0 0 22px; }}
    .content ul {{ margin:0 0 24px; padding-left:20px; }}
    .content li {{ margin:0 0 8px; }}
    .button-container {{ margin:34px 0; }}
    .btn {{ background:#111827; color:#ffffff!important; text-decoration:none; padding:12px 24px; border-radius:8px; font-size:14px; font-weight:600; display:inline-block; }}
    .fallback-link {{ font-size:13px; line-height:1.5; color:#86868b; word-break:break-word; }}
    .fallback-link a {{ color:#0066cc; text-decoration:none; }}
    .footer {{ margin-top:60px; border-top:1px solid #f5f5f7; padding-top:25px; font-size:13px; line-height:1.5; color:#86868b; }}
    .signature {{ font-weight:600; color:#000000; font-size:15px; margin-bottom:4px; }}
    .company {{ color:#1d1d1f; font-weight:500; }}
    @media (prefers-color-scheme: dark) {{
      body,.wrapper,.container {{ background:#0a0a0c!important; color:#e8e8ed!important; }}
      .header-table,.footer {{ border-color:#1c1c1e!important; }}
      .brand-title,.signature {{ color:#ffffff!important; }}
      .content,.company {{ color:#f5f5f7!important; }}
      .fallback-link,.footer {{ color:#86868b!important; }}
      .fallback-link a {{ color:#2997ff!important; }}
      .btn {{ background:#ffffff!important; color:#0a0a0c!important; }}
    }}
  </style>
</head>
<body>
  <div class="preheader">{preheader}</div>
  <table class="wrapper" width="100%" cellpadding="0" cellspacing="0" border="0">
    <tr>
      <td align="center">
        <table class="container" cellpadding="0" cellspacing="0" border="0">
          <tr>
            <td>
              <table class="header-table" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td class="brand-title" align="left">HeptaCert</td>
                  <td class="product-tag" align="right">Heptapus Group</td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td class="content" align="left">
              {body}
              {cta}
            </td>
          </tr>
          <tr>
            <td class="footer" align="left">
              <div class="signature">HeptaCert</div>
              <div class="company">Subsidiary, Heptapus Group</div>
              <div style="margin-top:8px;font-size:12px;">This email was generated by the HeptaCert secure verification infrastructure.</div>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>"""


SYSTEM_EMAIL_TEMPLATE_PRESETS = [
    {
        "name": "Sertifika Teslimi",
        "subject_tr": "Sertifikanız hazır | {{event_name}}",
        "subject_en": "Your certificate is ready | {{event_name}}",
        "body_html": _heptacert_email(
            "Your verified certificate is ready.",
            """
              <p>Merhaba {{recipient_name}},</p>
              <p>{{event_name}} için oluşturulan doğrulanabilir sertifikanız hazır.</p>
              <p>Sertifikanızı görüntüleyebilir, doğrulama bağlantısını paylaşabilir veya profesyonel profilinize ekleyebilirsiniz.</p>
            """,
            "Sertifikayı Görüntüle",
            "{{certificate_link}}",
        ),
    },
    {
        "name": "Kayıt Onayı",
        "subject_tr": "Kaydınız alındı | {{event_name}}",
        "subject_en": "Registration confirmed | {{event_name}}",
        "body_html": _heptacert_email(
            "Your event registration has been confirmed.",
            """
              <p>Merhaba {{recipient_name}},</p>
              <p>{{event_name}} için kaydınız başarıyla alındı.</p>
              <ul>
                <li><strong>Tarih:</strong> {{event_date}}</li>
                <li><strong>Yer:</strong> {{event_location}}</li>
              </ul>
              <p>Etkinlik güncellemelerini ve katılım detaylarını etkinlik sayfasından takip edebilirsiniz.</p>
            """,
            "Etkinlik Sayfasını Aç",
            "{{event_link}}",
        ),
    },
    {
        "name": "Katılım Teşekkürü",
        "subject_tr": "Katıldığınız için teşekkürler | {{event_name}}",
        "subject_en": "Thanks for attending | {{event_name}}",
        "body_html": _heptacert_email(
            "Thank you for attending.",
            """
              <p>Merhaba {{recipient_name}},</p>
              <p>{{event_name}} etkinliğine katıldığınız için teşekkür ederiz.</p>
              <p>Sertifika, sunum veya topluluk güncellemeleri hazır olduğunda sizi bilgilendireceğiz.</p>
            """,
            "Etkinlik Sayfası",
            "{{event_link}}",
        ),
    },
    {
        "name": "No-show Takibi",
        "subject_tr": "{{event_name}} etkinliğini kaçırdınız mı?",
        "subject_en": "Did you miss {{event_name}}?",
        "body_html": _heptacert_email(
            "We missed you at the event.",
            """
              <p>Merhaba {{recipient_name}},</p>
              <p>{{event_name}} için kaydınız vardı fakat katılım kaydı göremedik.</p>
              <p>Etkinlik özetini, gelecek programları ve varsa yeniden katılım fırsatlarını aşağıdaki bağlantıdan takip edebilirsiniz.</p>
            """,
            "Programı Görüntüle",
            "{{event_link}}",
        ),
    },
    {
        "name": "Anket Hatırlatma",
        "subject_tr": "Kısa anketinizi tamamlar mısınız? | {{event_name}}",
        "subject_en": "Please complete your short survey | {{event_name}}",
        "body_html": _heptacert_email(
            "Your feedback helps improve the experience.",
            """
              <p>Merhaba {{recipient_name}},</p>
              <p>{{event_name}} deneyimini iyileştirmek için kısa geri bildiriminize ihtiyacımız var.</p>
              <p>Anket yalnızca birkaç dakika sürer.</p>
            """,
            "Anketi Aç",
            "{{survey_link}}",
        ),
    },
    {
        "name": "LinkedIn Paylaşım Daveti",
        "subject_tr": "Başarınızı LinkedIn'de paylaşın | {{event_name}}",
        "subject_en": "Share your achievement on LinkedIn | {{event_name}}",
        "body_html": _heptacert_email(
            "Share your verified achievement on LinkedIn.",
            """
              <p>Merhaba {{recipient_name}},</p>
              <p>{{event_name}} sertifikanız başarıyla oluşturuldu ve HeptaCert doğrulama altyapısına tanımlandı.</p>
              <p>Bu başarıyı profesyonel ağınızla paylaşmak isterseniz aşağıdaki bağlantı doğrudan LinkedIn paylaşımı oluşturur.</p>
            """,
            "LinkedIn Paylaşımı Oluştur",
            "{{linkedin_share_link}}",
        ),
    },
    {
        "name": "Rozet Kazanımı",
        "subject_tr": "Yeni rozet kazandınız | {{event_name}}",
        "subject_en": "You earned a new badge | {{event_name}}",
        "body_html": _heptacert_email(
            "A new achievement badge was added to your wallet.",
            """
              <p>Tebrikler {{recipient_name}},</p>
              <p>{{event_name}} kapsamında yeni bir rozet kazandınız.</p>
              <p>Profilinizde rozetlerinizi, sertifikalarınızı ve etkinlik geçmişinizi görüntüleyebilirsiniz.</p>
            """,
            "Cüzdanı Aç",
            "{{wallet_link}}",
        ),
    },
    {
        "name": "Sertifika Yenileme Hatırlatma",
        "subject_tr": "Sertifikanızın süresi yaklaşıyor | {{event_name}}",
        "subject_en": "Your certificate is expiring soon | {{event_name}}",
        "body_html": _heptacert_email(
            "Your certificate renewal window is approaching.",
            """
              <p>Merhaba {{recipient_name}},</p>
              <p>{{event_name}} sertifikanızın geçerlilik süresi yaklaşıyor.</p>
              <p>Yenileme adımlarını takip etmek veya ilgili programa yeniden katılmak için etkinlik sayfasını ziyaret edebilirsiniz.</p>
            """,
            "Yenileme Adımlarını Gör",
            "{{event_link}}",
        ),
    },
    {
        "name": "CRM Takip Maili",
        "subject_tr": "{{event_name}} sonrası kısa takip",
        "subject_en": "Quick follow-up after {{event_name}}",
        "body_html": _heptacert_email(
            "A short follow-up from the event team.",
            """
              <p>Merhaba {{recipient_name}},</p>
              <p>{{event_name}} sonrasında sizinle tekrar iletişime geçmek istedik.</p>
              <p>Sorularınız, eğitim ihtiyaçlarınız veya kurumsal talepleriniz varsa bu e-postayı yanıtlayabilirsiniz.</p>
            """,
            "Etkinlik Detayları",
            "{{event_link}}",
        ),
    },
]

