"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import {
  ArrowLeft, Loader2, AlertCircle, Copy, Eye, EyeOff,
  Check, ShieldCheck, ShieldAlert,
} from "lucide-react";
import Link from "next/link";
import { get2FAStatus, setup2FA, enable2FA, disable2FA, TwoFAStatusOut } from "@/lib/api";
import { useI18n } from "@/lib/i18n";
import { AnimatePresence, motion } from "framer-motion";

export default function TwoFAManagementPage() {
  const router = useRouter();
  const { lang } = useI18n();
  const isTr = lang === "tr";

  const copy = {
    title:          isTr ? "İki Faktörlü Kimlik Doğrulama (2FA)" : "Two-Factor Authentication (2FA)",
    subtitle:       isTr ? "Platform giriş güvenliğinizi en üst düzeye taşıyın." : "Maximize your platform login security.",
    loadFailed:     isTr ? "2FA durumu yüklenemedi" : "Failed to load 2FA status",
    setupFailed:    isTr ? "2FA kurulumu başarısız" : "2FA setup failed",
    codeRequired:   isTr ? "Doğrulama kodu gerekli" : "Verification code is required",
    enableFailed:   isTr ? "2FA etkinleştirilemedi" : "Failed to enable 2FA",
    passRequired:   isTr ? "Şifre gerekli" : "Password is required",
    disableFailed:  isTr ? "2FA devre dışı bırakılamadı" : "Failed to disable 2FA",
    currentStatus:  isTr ? "Mevcut Durum" : "Current Status",
    enabled:        isTr ? "Etkinleştirildi (Güvenli)" : "Enabled (Secure)",
    disabled:       isTr ? "Devre Dışı (Risk Altında)" : "Disabled (At Risk)",
    setupStepsTitle: isTr ? "Güvenli Kurulum Adımları" : "Setup Steps",
    setupSteps:     isTr ? [
      "Aşağıdaki butona tıklayarak sistem tarafından üretilecek özel kurulum kodunu alın.",
      "Mobil cihazınıza Google Authenticator, Microsoft Authenticator veya Authy uygulamasını indirin.",
      "Uygulama içerisinden kamerayı açıp QR kodunu taratın veya alternatif olarak gizli anahtarı girin.",
      "Uygulamanın anlık ürettiği 6 haneli doğrulama kodunu ekrana yazarak sistemi aktif hale getirin.",
    ] : [
      "Click the button below to receive your unique setup code.",
      "Install Google Authenticator, Microsoft Authenticator, or Authy on your mobile device.",
      "Open the app, scan the QR code with the camera, or enter the secret key manually.",
      "Enter the 6-digit code generated by the app to activate two-factor authentication.",
    ],
    startSetup:     isTr ? "2FA Kurulumunu Başlat" : "Start 2FA Setup",
    backupCodes:    isTr ? "Güvenlik Yedek Kodları" : "Backup Codes",
    backupCodesDesc: isTr
      ? "Telefonunuza veya doğrulama uygulamanıza erişemediğiniz acil durumlar için bu kodları güvenli bir alanda saklayın."
      : "Store these codes in a safe place for emergencies when you can't access your phone or authenticator app.",
    removeTitle:    isTr ? "2FA Güvenliğini Kaldır" : "Remove 2FA Security",
    removeDesc:     isTr
      ? "İki faktörlü kimlik doğrulamayı devre dışı bırakmak hesabınızı saldırılara karşı savunmasız hale getirecektir. Devam etmek için şifrenizi girin."
      : "Disabling two-factor authentication will leave your account vulnerable to attacks. Enter your password to continue.",
    passPlaceholder: isTr ? "Mevcut şifrenizi yazın" : "Enter your current password",
    disabling:      isTr ? "Devre Dışı Bırakılıyor..." : "Disabling...",
    disableBtn:     isTr ? "2FA Güvenliğini Kapat" : "Disable 2FA",
    setupTitle:     isTr ? "2FA Kurulumunu Tamamla" : "Complete 2FA Setup",
    setupDesc:      isTr ? "Aşağıdaki karekodu authenticator uygulamanıza taratın." : "Scan the QR code below with your authenticator app.",
    altKey:         isTr ? "Alternatif Gizli Anahtar" : "Alternative Secret Key",
    codeLabel:      isTr ? "Uygulamadaki 6 Haneli Kod" : "6-Digit Code from App",
    cancel:         isTr ? "İptal" : "Cancel",
    verifying:      isTr ? "Doğrulanıyor..." : "Verifying...",
    activate:       isTr ? "Etkinleştir" : "Activate",
  };

  const [status, setStatus] = useState<TwoFAStatusOut | null>(null);
  const [setupData, setSetupData] = useState<TwoFAStatusOut | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showSecret, setShowSecret] = useState(false);
  const [copied, setCopied] = useState(false);
  const [verificationCode, setVerificationCode] = useState("");
  const [verifying, setVerifying] = useState(false);
  const [disablePassword, setDisablePassword] = useState("");
  const [disabling, setDisabling] = useState(false);
  const [showSetupModal, setShowSetupModal] = useState(false);

  useEffect(() => { fetchStatus(); }, []);

  const fetchStatus = async () => {
    try {
      setError(null);
      setStatus(await get2FAStatus());
    } catch (e: any) {
      setError(e?.message || copy.loadFailed);
    } finally {
      setLoading(false);
    }
  };

  const handleSetupClick = async () => {
    try {
      setError(null);
      setSetupData(await setup2FA());
      setShowSetupModal(true);
    } catch (e: any) {
      setError(e?.message || copy.setupFailed);
    }
  };

  const handleEnable = async () => {
    if (!verificationCode.trim()) { setError(copy.codeRequired); return; }
    try {
      setVerifying(true);
      setError(null);
      await enable2FA(verificationCode);
      await fetchStatus();
      setShowSetupModal(false);
      setVerificationCode("");
    } catch (e: any) {
      setError(e?.message || copy.enableFailed);
    } finally {
      setVerifying(false);
    }
  };

  const handleDisable = async () => {
    if (!disablePassword.trim()) { setError(copy.passRequired); return; }
    try {
      setDisabling(true);
      setError(null);
      await disable2FA(disablePassword);
      await fetchStatus();
      setDisablePassword("");
    } catch (e: any) {
      setError(e?.message || copy.disableFailed);
    } finally {
      setDisabling(false);
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="flex w-full items-center justify-center p-24">
        <Loader2 className="h-6 w-6 animate-spin text-surface-400 stroke-[2.5]" />
      </div>
    );
  }

  return (
    <div className="w-full max-w-2xl mx-auto p-4 sm:p-6 antialiased text-surface-900 space-y-6">
      <div className="flex items-center gap-3.5 pb-2">
        <Link
          href="/admin/settings"
          className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-surface-200 bg-white text-surface-500 shadow-sm hover:bg-surface-50 transition-all active:scale-95"
        >
          <ArrowLeft className="h-4 w-4 stroke-[2.5]" />
        </Link>
        <div className="min-w-0">
          <h1 className="text-base font-bold tracking-tight text-surface-900 sm:text-lg">{copy.title}</h1>
          <p className="text-xs text-surface-400">{copy.subtitle}</p>
        </div>
      </div>

      {error && (
        <div className="rounded-xl border border-red-100 bg-red-50/40 p-4 text-xs font-semibold text-red-600 flex items-center gap-2">
          <AlertCircle className="h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <div className={`rounded-2xl border p-5 shadow-sm transition-all duration-300 ${status?.is_enabled ? "border-emerald-200 bg-emerald-50/10" : "border-amber-200 bg-amber-50/10"}`}>
        <div className="flex items-center gap-4">
          <div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border shadow-sm ${status?.is_enabled ? "border-emerald-100 bg-emerald-50 text-emerald-600" : "border-amber-100 bg-amber-50 text-amber-600"}`}>
            {status?.is_enabled ? <ShieldCheck className="h-5 w-5 stroke-[2]" /> : <ShieldAlert className="h-5 w-5 stroke-[2]" />}
          </div>
          <div className="min-w-0 space-y-0.5">
            <p className="text-11 font-bold uppercase tracking-wider text-surface-400">{copy.currentStatus}</p>
            <h2 className={`text-base font-bold tracking-tight ${status?.is_enabled ? "text-emerald-700" : "text-amber-700"}`}>
              {status?.is_enabled ? copy.enabled : copy.disabled}
            </h2>
          </div>
        </div>
      </div>

      {!status?.is_enabled && (
        <div className="rounded-2xl border border-surface-200 bg-white p-5 sm:p-6 shadow-sm space-y-4">
          <h2 className="text-xs font-bold uppercase tracking-wider text-surface-900 border-b border-surface-100 pb-2.5">{copy.setupStepsTitle}</h2>
          <div className="relative pl-4 before:absolute before:bottom-1 before:left-1 before:top-1 before:w-[1px] before:bg-surface-100">
            <div className="space-y-4 text-xs font-medium text-surface-500 leading-relaxed">
              {copy.setupSteps.map((step, index) => (
                <div key={index} className="relative group flex items-start gap-3">
                  <div className="absolute -left-[19.5px] top-0.5 flex h-2 w-2 items-center justify-center rounded-full bg-white ring-4 ring-white border border-surface-300 group-hover:border-surface-900 transition-colors" />
                  <p className="flex-1"><strong className="text-surface-900 mr-1">{index + 1}.</strong> {step}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {!status?.is_enabled && (
        <button
          onClick={handleSetupClick}
          className="w-full inline-flex min-h-[42px] items-center justify-center rounded-lg bg-surface-900 text-xs font-semibold text-white transition hover:bg-surface-800 active:scale-[0.98] shadow-sm"
        >
          {copy.startSetup}
        </button>
      )}

      {status?.is_enabled && (status as any)?.recovery_codes?.length > 0 && (
        <div className="rounded-2xl border border-surface-200 bg-white p-5 shadow-sm space-y-4">
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-surface-900">{copy.backupCodes}</h2>
            <p className="mt-1 text-xs text-surface-400">{copy.backupCodesDesc}</p>
          </div>
          <div className="grid grid-cols-2 gap-2">
            {(status as any).recovery_codes.map((code: string, idx: number) => (
              <div key={idx} className="bg-surface-50/50 border border-surface-100 rounded-xl p-2.5 font-mono text-xs font-semibold text-surface-800 text-center tracking-wide">
                {code}
              </div>
            ))}
          </div>
        </div>
      )}

      {status?.is_enabled && (
        <div className="rounded-2xl border border-surface-200 bg-white p-5 shadow-sm space-y-4">
          <div>
            <h2 className="text-xs font-bold uppercase tracking-wider text-red-600">{copy.removeTitle}</h2>
            <p className="mt-1 text-xs text-surface-400">{copy.removeDesc}</p>
          </div>
          <input
            type="password"
            placeholder={copy.passPlaceholder}
            value={disablePassword}
            onChange={(e) => setDisablePassword(e.target.value)}
            className="input"
            disabled={disabling}
          />
          <button
            onClick={handleDisable}
            disabled={disabling || !disablePassword}
            className="w-full inline-flex min-h-[38px] items-center justify-center rounded-lg bg-red-500 text-xs font-semibold text-white transition hover:bg-red-600 active:scale-[0.98] disabled:opacity-40 shadow-sm"
          >
            {disabling ? (
              <span className="flex items-center gap-1.5"><Loader2 className="h-3.5 w-3.5 animate-spin" />{copy.disabling}</span>
            ) : copy.disableBtn}
          </button>
        </div>
      )}

      <AnimatePresence>
        {showSetupModal && setupData && (
          <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="absolute inset-0 bg-surface-800/20 backdrop-blur-md"
              onClick={() => { if (!verifying) { setShowSetupModal(false); setVerificationCode(""); } }}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.96, y: 8 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.96, y: 8 }}
              className="relative z-10 w-full max-w-sm overflow-hidden rounded-2xl border border-surface-200 bg-white/95 p-6 shadow-xl backdrop-blur-xl space-y-4"
            >
              <div>
                <h2 className="text-sm font-bold text-surface-900 tracking-tight">{copy.setupTitle}</h2>
                <p className="mt-1 text-11 text-surface-400">{copy.setupDesc}</p>
              </div>

              <div className="bg-surface-50 border border-surface-100 rounded-xl p-4 flex justify-center shadow-inner">
                {setupData.qr_code && (
                  <img src={setupData.qr_code} alt="2FA QR Code" className="w-52 h-52 object-contain mix-blend-multiply" />
                )}
              </div>

              <div className="space-y-1.5">
                <p className="text-11 font-bold text-surface-500">{copy.altKey}</p>
                <div className="flex items-center gap-1.5">
                  <input
                    type={showSecret ? "text" : "password"}
                    value={setupData.secret}
                    readOnly
                    className="flex-1 min-h-[34px] px-3 rounded-xl border border-surface-200 font-mono text-xs bg-surface-50/50 text-surface-800 font-semibold outline-none"
                  />
                  <button type="button" onClick={() => setShowSecret(!showSecret)} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border border-surface-200 bg-white text-surface-400 hover:border-surface-300 hover:text-surface-900 transition-all shadow-sm">
                    {showSecret ? <EyeOff className="h-3.5 w-3.5 stroke-[2]" /> : <Eye className="h-3.5 w-3.5 stroke-[2]" />}
                  </button>
                  <button type="button" onClick={() => setupData.secret && copyToClipboard(setupData.secret)} className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border border-surface-200 bg-white text-surface-400 hover:border-surface-300 hover:text-surface-900 transition-all shadow-sm">
                    {copied ? <Check className="h-3.5 w-3.5 text-emerald-500 stroke-[2.5]" /> : <Copy className="h-3.5 w-3.5 stroke-[2]" />}
                  </button>
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="block text-11 font-bold text-surface-500">{copy.codeLabel}</label>
                <input
                  type="text"
                  placeholder="000 000"
                  value={verificationCode}
                  onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                  maxLength={6}
                  className="w-full min-h-[46px] rounded-xl border border-surface-200 bg-white px-4 text-center text-xl font-bold tracking-[0.25em] outline-none transition focus:border-surface-900 focus:ring-1 focus:ring-surface-900 placeholder:text-surface-300 placeholder:tracking-normal"
                />
              </div>

              <div className="flex gap-2 pt-1">
                <button
                  type="button"
                  onClick={() => { setShowSetupModal(false); setVerificationCode(""); }}
                  className="flex-1 rounded-xl border border-surface-200 bg-white px-4 py-2.5 text-xs font-semibold text-surface-700 shadow-sm transition hover:bg-surface-50 active:scale-[0.98]"
                >
                  {copy.cancel}
                </button>
                <button
                  type="button"
                  onClick={handleEnable}
                  disabled={verifying || verificationCode.length !== 6}
                  className="flex-1 inline-flex items-center justify-center rounded-lg bg-surface-900 px-4 py-2.5 text-xs font-semibold text-white shadow-sm transition hover:bg-surface-800 active:scale-[0.98] disabled:opacity-30"
                >
                  {verifying ? (
                    <span className="flex items-center gap-1.5"><Loader2 className="h-3.5 w-3.5 animate-spin" />{copy.verifying}</span>
                  ) : copy.activate}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
